# Generated by Django 3.2.5 on 2022-09-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='case_status_eac_lb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=16)),
                ('form', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=64)),
                ('action_date', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='case_status_eac_sc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=16)),
                ('form', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=64)),
                ('action_date', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='case_status_ioe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=16)),
                ('form', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=64)),
                ('action_date', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='case_status_lin_lb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=16)),
                ('form', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=64)),
                ('action_date', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='case_status_lin_sc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=16)),
                ('form', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=64)),
                ('action_date', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='case_status_msc_lb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=16)),
                ('form', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=64)),
                ('action_date', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='case_status_msc_sc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=16)),
                ('form', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=64)),
                ('action_date', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='case_status_src_lb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=16)),
                ('form', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=64)),
                ('action_date', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='case_status_src_sc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=16)),
                ('form', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=64)),
                ('action_date', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='case_status_wac_lb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=16)),
                ('form', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=64)),
                ('action_date', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='case_status_wac_sc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=16)),
                ('form', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=64)),
                ('action_date', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='case_status_ysc_lb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=16)),
                ('form', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=64)),
                ('action_date', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='case_status_ysc_sc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=16)),
                ('form', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=64)),
                ('action_date', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='center_running',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_lsi', models.CharField(choices=[('LIN_LB', 'LIN_LB'), ('MSC_LB', 'MSC_LB'), ('SRC_LB', 'SRC_LB'), ('WAC_LB', 'WAC_LB'), ('EAC_LB', 'EAC_LB'), ('YSC_LB', 'YSC_LB'), ('LIN_SC', 'LIN_SC'), ('MSC_SC', 'MSC_SC'), ('SRC_SC', 'SRC_SC'), ('WAC_SC', 'WAC_SC'), ('EAC_SC', 'EAC_SC'), ('YSC_SC', 'YSC_SC'), ('IOE', 'IOE')], default='', max_length=32)),
                ('status', models.CharField(max_length=16)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('update_day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('l1', models.CharField(max_length=64)),
                ('l2', models.CharField(max_length=32)),
                ('l3', models.CharField(max_length=16)),
                ('l4', models.CharField(max_length=16)),
                ('note', models.CharField(max_length=256)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='status_daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(max_length=16)),
                ('received_n', models.IntegerField()),
                ('rfe_n', models.IntegerField()),
                ('approved_n', models.IntegerField()),
                ('fp_schduled_n', models.IntegerField()),
                ('fp_taken_n', models.IntegerField()),
                ('iv_schduled_n', models.IntegerField()),
                ('iv_done_n', models.IntegerField()),
                ('rejected_n', models.IntegerField()),
                ('terminated_n', models.IntegerField()),
                ('transferred_n', models.IntegerField()),
                ('others_n', models.IntegerField()),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sysparam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centers', models.CharField(max_length=64)),
                ('fiscal_year_n', models.IntegerField()),
                ('crawler_time', models.TimeField()),
                ('crawler_number', models.IntegerField()),
                ('sys_status', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='visabulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableAB', models.CharField(max_length=8)),
                ('category', models.CharField(default='', max_length=64)),
                ('conutry', models.CharField(choices=[('CHINA', 'China'), ('INDIA', 'India'), ('MEXICO', 'Mexico'), ('PHILIPPINES', 'Philippines'), ('EGH', 'El Salvador\\Guatemala\\Honduras'), ('OTHERS', 'Others')], default='', max_length=32)),
                ('formonth', models.DateField()),
                ('visadate', models.CharField(max_length=128)),
                ('pubdate', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
