# Generated by Django 3.2.5 on 2022-09-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycase', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='case_status_eac_lb',
            constraint=models.UniqueConstraint(fields=('receipt_number', 'status'), name='unique_receipt_status_eac_lb'),
        ),
        migrations.AddConstraint(
            model_name='case_status_eac_sc',
            constraint=models.UniqueConstraint(fields=('receipt_number', 'status'), name='unique_receipt_status_eac_sc'),
        ),
        migrations.AddConstraint(
            model_name='case_status_ioe',
            constraint=models.UniqueConstraint(fields=('receipt_number', 'status'), name='unique_receipt_status_ioe'),
        ),
        migrations.AddConstraint(
            model_name='case_status_lin_lb',
            constraint=models.UniqueConstraint(fields=('receipt_number', 'status'), name='unique_receipt_status_lin_lb'),
        ),
        migrations.AddConstraint(
            model_name='case_status_lin_sc',
            constraint=models.UniqueConstraint(fields=('receipt_number', 'status'), name='unique_receipt_status_lin_sc'),
        ),
        migrations.AddConstraint(
            model_name='case_status_msc_lb',
            constraint=models.UniqueConstraint(fields=('receipt_number', 'status'), name='unique_receipt_status_msc_lb'),
        ),
        migrations.AddConstraint(
            model_name='case_status_msc_sc',
            constraint=models.UniqueConstraint(fields=('receipt_number', 'status'), name='unique_receipt_status_msc_sc'),
        ),
        migrations.AddConstraint(
            model_name='case_status_src_lb',
            constraint=models.UniqueConstraint(fields=('receipt_number', 'status'), name='unique_receipt_status_src_lb'),
        ),
        migrations.AddConstraint(
            model_name='case_status_src_sc',
            constraint=models.UniqueConstraint(fields=('receipt_number', 'status'), name='unique_receipt_status_src_sc'),
        ),
        migrations.AddConstraint(
            model_name='case_status_wac_lb',
            constraint=models.UniqueConstraint(fields=('receipt_number', 'status'), name='unique_receipt_status_wac_lb'),
        ),
        migrations.AddConstraint(
            model_name='case_status_wac_sc',
            constraint=models.UniqueConstraint(fields=('receipt_number', 'status'), name='unique_receipt_status_wac_sc'),
        ),
        migrations.AddConstraint(
            model_name='case_status_ysc_lb',
            constraint=models.UniqueConstraint(fields=('receipt_number', 'status'), name='unique_receipt_status_ysc_lb'),
        ),
        migrations.AddConstraint(
            model_name='case_status_ysc_sc',
            constraint=models.UniqueConstraint(fields=('receipt_number', 'status'), name='unique_receipt_status_ysc_sc'),
        ),
    ]
