# Generated by Django 3.2.5 on 2022-09-06 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycase', '0002_auto_20220905_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_status_eac_lb',
            name='action_date_x',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='case_status_eac_sc',
            name='action_date_x',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='case_status_ioe',
            name='action_date_x',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='case_status_lin_lb',
            name='action_date_x',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='case_status_lin_sc',
            name='action_date_x',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='case_status_msc_lb',
            name='action_date_x',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='case_status_msc_sc',
            name='action_date_x',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='case_status_src_lb',
            name='action_date_x',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='case_status_src_sc',
            name='action_date_x',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='case_status_wac_lb',
            name='action_date_x',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='case_status_wac_sc',
            name='action_date_x',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='case_status_ysc_lb',
            name='action_date_x',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='case_status_ysc_sc',
            name='action_date_x',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
