# Generated by Django 3.2.5 on 2022-09-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycase', '0003_auto_20220906_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_daily',
            name='form',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visabulletin',
            name='conutry',
            field=models.CharField(choices=[('CHINA', 'China'), ('INDIA', 'India'), ('MEXICO', 'Mexico'), ('PHILIPPINES', 'Philippines'), ('EGH', 'El Salvador/Guatemala/Honduras'), ('OTHERS', 'Others')], default='', max_length=32),
        ),
    ]
