# Generated by Django 3.2.5 on 2022-10-04 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycase', '0003_auto_20220925_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visabulletin',
            old_name='tableAB',
            new_name='tableA',
        ),
        migrations.RemoveField(
            model_name='visabulletin',
            name='pubdate',
        ),
        migrations.AddField(
            model_name='visabulletin',
            name='EBFB',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='visabulletin',
            name='adddate',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 22, 56, 23, 518103)),
        ),
        migrations.AddField(
            model_name='visabulletin',
            name='tableB',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
