# Generated by Django 3.2.5 on 2022-10-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycase', '0005_auto_20221004_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visabulletin',
            name='adddate',
            field=models.DateField(auto_now=True),
        ),
    ]
