# Generated by Django 3.2.5 on 2022-09-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycase', '0006_auto_20220910_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_status_eac_lb',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='case_status_eac_sc',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='case_status_ioe',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='case_status_lin_lb',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='case_status_lin_sc',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='case_status_msc_lb',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='case_status_msc_sc',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='case_status_src_lb',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='case_status_src_sc',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='case_status_wac_lb',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='case_status_wac_sc',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='case_status_ysc_lb',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='case_status_ysc_sc',
            name='status',
            field=models.CharField(max_length=128),
        ),
    ]
