# Generated by Django 3.2.5 on 2022-10-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycase', '0006_alter_visabulletin_adddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='status_trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_status', models.CharField(max_length=128)),
                ('dest_status', models.CharField(max_length=128)),
                ('count', models.IntegerField()),
                ('action_date', models.DateField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('date_number', models.IntegerField()),
                ('note', models.CharField(max_length=64)),
            ],
        ),
    ]
