# Generated by Django 3.2.5 on 2022-09-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycase', '0007_auto_20220910_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_status_eac_lb',
            name='case_stage',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='case_status_eac_sc',
            name='case_stage',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='case_status_ioe',
            name='case_stage',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='case_status_lin_lb',
            name='case_stage',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='case_status_lin_sc',
            name='case_stage',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='case_status_msc_lb',
            name='case_stage',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='case_status_msc_sc',
            name='case_stage',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='case_status_src_lb',
            name='case_stage',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='case_status_src_sc',
            name='case_stage',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='case_status_wac_lb',
            name='case_stage',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='case_status_wac_sc',
            name='case_stage',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='case_status_ysc_lb',
            name='case_stage',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='case_status_ysc_sc',
            name='case_stage',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='case_status_eac_lb',
            name='action_date',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='case_status_eac_sc',
            name='action_date',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='case_status_ioe',
            name='action_date',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='case_status_lin_lb',
            name='action_date',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='case_status_lin_sc',
            name='action_date',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='case_status_msc_lb',
            name='action_date',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='case_status_msc_sc',
            name='action_date',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='case_status_src_lb',
            name='action_date',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='case_status_src_sc',
            name='action_date',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='case_status_wac_lb',
            name='action_date',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='case_status_wac_sc',
            name='action_date',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='case_status_ysc_lb',
            name='action_date',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='case_status_ysc_sc',
            name='action_date',
            field=models.CharField(max_length=32),
        ),
    ]
