# Generated by Django 3.2.5 on 2022-10-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycase', '0007_status_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_trans',
            name='center',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
