# Generated by Django 3.2.5 on 2022-10-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycase', '0008_status_trans_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_trans',
            name='fiscal_year',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status_trans',
            name='form_type',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
