# Generated by Django 3.2.5 on 2022-09-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycase', '0009_auto_20220916_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_daily',
            name='new_n',
            field=models.IntegerField(default=0),
        ),
    ]
