# Generated by Django 3.2.5 on 2022-11-17 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycase', '0010_auto_20221011_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_status_mct_lb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=16)),
                ('form', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=128)),
                ('action_date', models.CharField(max_length=32)),
                ('action_date_x', models.DateField(default=datetime.date.today)),
                ('case_stage', models.CharField(default='', max_length=32)),
                ('rd_date', models.DateField(default=datetime.date(2000, 1, 1), verbose_name='date received')),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='case_status_mct_sc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=16)),
                ('form', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=128)),
                ('action_date', models.CharField(max_length=32)),
                ('action_date_x', models.DateField(default=datetime.date.today)),
                ('case_stage', models.CharField(default='', max_length=32)),
                ('rd_date', models.DateField(default=datetime.date(2000, 1, 1), verbose_name='date received')),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('date_number', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='case_status_mct_sc',
            constraint=models.UniqueConstraint(fields=('receipt_number', 'status', 'action_date_x'), name='unique_receipt_status_datex_mct_sc'),
        ),
        migrations.AddConstraint(
            model_name='case_status_mct_lb',
            constraint=models.UniqueConstraint(fields=('receipt_number', 'status', 'action_date_x'), name='unique_receipt_status_datex_mct_lb'),
        ),
    ]
