
status_dict = {
    "Special Immigrant Juvenile Deferred Action Granted":{"l1":"ActionGranted","l2":"Approved","l3":"Approved","l4":"Final"},
    "Appeal Was Approved":{"l1":"Approved","l2":"Approved","l3":"Approved","l4":"Final"},
    "Case Approval Was Affirmed":{"l1":"Approved","l2":"Approved","l3":"Approved","l4":"Final"},
    "Case Approval Was Certified By USCIS":{"l1":"Approved","l2":"Approved","l3":"Approved","l4":"Final"},
    "Case Approval Was Reaffirmed And Mailed Back To Department Of State":{"l1":"Approved","l2":"Approved","l3":"Approved","l4":"Final"},
    "Case Was Approved":{"l1":"Approved","l2":"Approved","l3":"Approved","l4":"Final"},
    "Case Was Approved And A Decision Notice Was Sent":{"l1":"Approved","l2":"Approved","l3":"Approved","l4":"Final"},
    "Case Was Approved And My Decision Was Emailed":{"l1":"Approved","l2":"Approved","l3":"Approved","l4":"Final"},
    "Case Was Approved And USCIS Notified The U.S. Consulate or Port of Entry":{"l1":"Approved","l2":"Approved","l3":"Approved","l4":"Final"},
    "Request For A Duplicate Card Was Approved":{"l1":"Approved","l2":"Approved","l3":"Approved","l4":"Final"},
    "Special Immigrant Juvenile Form I-360 Approved With Deferred Action":{"l1":"Approved","l2":"Approved","l3":"Approved","l4":"Final"},
    "Biometrics Appointment Was Scheduled":{"l1":"FP_Scheduled","l2":"FP_Scheduled","l3":"Received","l4":"Processing"},
    "Fingerprint and Biometrics Appointment Was Scheduled":{"l1":"FP_Scheduled","l2":"FP_Scheduled","l3":"Received","l4":"Processing"},
    "Case Was Updated To Show Fingerprints Were Taken":{"l1":"FP_Taken","l2":"FP_Taken","l3":"FP_Taken","l4":"Processing"},
    "Case Is On Hold":{"l1":"Hold","l2":"Hold","l3":"Received","l4":"Processing"},
    "Case Is On Hold Because Of Pending Litigation":{"l1":"Hold","l2":"Hold","l3":"Received","l4":"Processing"},
    "Intent To Rescind Notice Was Mailed":{"l1":"IntentToRescind","l2":"NoticeSent","l3":"Other","l4":"Other"},
    "CWR Notice of Intent to Revoke Sent":{"l1":"IntentToRevoke","l2":"NoticeSent","l3":"Other","l4":"Other"},
    "Intent to Revoke Notice Was Sent":{"l1":"IntentToRevoke","l2":"NoticeSent","l3":"Other","l4":"Other"},
    "Notice Of USCIS' Intent To Terminate My Status Was Mailed":{"l1":"IntentToTerminate","l2":"NoticeSent","l3":"Other","l4":"Other"},
    "Interview Was Completed And My Case Must Be Reviewed":{"l1":"InterviewCompleted","l2":"InterviewCompleted","l3":"Interviewed","l4":"Processing"},
    "Case is Ready to Be Scheduled for An Interview":{"l1":"InterviewScheduled","l2":"InterviewScheduled","l3":"Interviewed","l4":"Processing"},
    "Case Was Transferred To Schedule An Interview":{"l1":"InterviewScheduled","l2":"InterviewScheduled","l3":"Interviewed","l4":"Processing"},
    "Interview Is Scheduled":{"l1":"InterviewScheduled","l2":"InterviewScheduled","l3":"Interviewed","l4":"Processing"},
    "Interview Was Rescheduled":{"l1":"InterviewScheduled","l2":"InterviewScheduled","l3":"Interviewed","l4":"Processing"},
    "Interview Was Scheduled":{"l1":"InterviewScheduled","l2":"InterviewScheduled","l3":"Interviewed","l4":"Processing"},
    "Card Was Delivered To Me By The Post Office":{"l1":"Mailed","l2":"Mailed","l3":"Approved","l4":"Final"},
    "Card Was Determined As Undeliverable By The Post Office":{"l1":"Mailed","l2":"Mailed","l3":"Approved","l4":"Final"},
    "Card Was Mailed To Me":{"l1":"Mailed","l2":"Mailed","l3":"Approved","l4":"Final"},
    "Card Was Picked Up By The United States Postal Service":{"l1":"Mailed","l2":"Mailed","l3":"Approved","l4":"Final"},
    "Document Was Mailed":{"l1":"Mailed","l2":"Mailed","l3":"Approved","l4":"Final"},
    "Document Was Mailed But Not Returned To USCIS":{"l1":"Mailed","l2":"Mailed","l3":"Approved","l4":"Final"},
    "Document Was Mailed To Me":{"l1":"Mailed","l2":"Mailed","l3":"Approved","l4":"Final"},
    "Document Was Personally Delivered To Me":{"l1":"Mailed","l2":"Mailed","l3":"Approved","l4":"Final"},
    "Travel Document Was Mailed":{"l1":"Mailed","l2":"Mailed","l3":"Approved","l4":"Final"},
    "Duplicate Notice Was Mailed":{"l1":"NoticeSent","l2":"NoticeSent","l3":"Other","l4":"Other"},
    "Eligibility Notice Was Mailed":{"l1":"NoticeSent","l2":"NoticeSent","l3":"Other","l4":"Other"},
    "Litigation Notice Was Mailed":{"l1":"NoticeSent","l2":"NoticeSent","l3":"Other","l4":"Other"},
    "Notice Explaining Actions Mailed":{"l1":"NoticeSent","l2":"NoticeSent","l3":"Other","l4":"Other"},
    "Notice Explaining USCIS Actions Was Mailed":{"l1":"NoticeSent","l2":"NoticeSent","l3":"Other","l4":"Other"},
    "Amended Notice Was Mailed":{"l1":"NoticeSent","l2":"NoticeSent","l3":"Other","l4":"Other"},
    "CASE STATUS":{"l1":"Invalid","l2":"Other","l3":"Other","l4":"Other"},
    "Case Was Updated To Show That No One Appeared for In-Person Processing":{"l1":"NoneAppeared","l2":"Other","l3":"Other","l4":"Other"},
    "Case Was Not Revoked or Cancelled By USCIS":{"l1":"NotRevoked","l2":"Other","l3":"Other","l4":"Other"},
    "Premium Processing Case is Eligible for Pre-Certification":{"l1":"PP_Eligible","l2":"Other","l3":"Other","l4":"Other"},
    "Prequalified Decision Notice Was Mailed":{"l1":"Prequalified","l2":"Other","l3":"Other","l4":"Other"},
    "Sent to CDC for Opinion":{"l1":"SentCDC","l2":"Other","l3":"Other","l4":"Other"},
    "Case Remains Pending":{"l1":"Pending","l2":"Pending","l3":"Received","l4":"Processing"},
    "Case Is Pending at a Local Office":{"l1":"PendingLO","l2":"Pending","l3":"Received","l4":"Processing"},
    "Visa Bulletin Not Current Or Case Held In Abeyance":{"l1":"NotCurrent","l2":"Pending","l3":"Received","l4":"Processing"},
    "Advance Parole Document Was Produced":{"l1":"Produced","l2":"Produced","l3":"Approved","l4":"Final"},
    "New Card Is Being Produced":{"l1":"Produced","l2":"Produced","l3":"Approved","l4":"Final"},
    "Permanent Resident Card Is Being Produced":{"l1":"Produced","l2":"Produced","l3":"Approved","l4":"Final"},
    "Reentry Permit Was Produced":{"l1":"Produced","l2":"Produced","l3":"Approved","l4":"Final"},
    "Refugee Travel Document Was Produced":{"l1":"Produced","l2":"Produced","l3":"Approved","l4":"Final"},
    "Appeal Was Remanded To The Originating Office For Consideration":{"l1":"Amended","l2":"Received","l3":"Received","l4":"Processing"},
    "Appointment Notice Was Mailed":{"l1":"AppointmentSchuduled","l2":"Received","l3":"Received","l4":"Processing"},
    "Request To Reschedule My Appointment Was Received":{"l1":"AppointmentSchuduled","l2":"Received","l3":"Received","l4":"Processing"},
    "Signature Card Was Received":{"l1":"CardReceived","l2":"Received","l3":"Received","l4":"Processing"},
    "Visa Bulletin Current":{"l1":"Current","l2":"Received","l3":"Received","l4":"Processing"},
    "Expedite Request Approved":{"l1":"ER_Approved","l2":"Received","l3":"Received","l4":"Processing"},
    "Expedite Request Denied":{"l1":"ER_Denied","l2":"Received","l3":"Received","l4":"Processing"},
    "Expedite Request Received":{"l1":"ER_Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Resubmitted Fee Was Not Accepted":{"l1":"FeeNotAccepted","l2":"Received","l3":"Received","l4":"Processing"},
    "Fees Were Waived":{"l1":"FeeWaived","l2":"Received","l3":"Received","l4":"Processing"},
    "Interview Cancelled":{"l1":"InterviewCancelled","l2":"Received","l3":"Received","l4":"Processing"},
    "Interview Cancelled And Notice Ordered":{"l1":"InterviewCancelled","l2":"Received","l3":"Received","l4":"Processing"},
    "Request For Premium Processing Services Was Received":{"l1":"PP_Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Card Was Received By USCIS Along With My Letter":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Case Accepted By The USCIS Lockbox":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Case Required USCIS To Send A Notice":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Case Was Received":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Case Was Received and A Receipt Notice Was Sent":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Case Was Received At Another USCIS Office":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Case Was Returned To USCIS By The Executive Office of Immigration Review":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "CNMI Semiannual Report Received":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Continuation Notice Was Mailed":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Correspondence Was Received And USCIS Is Reviewing It":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Date of Birth Was Updated":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Document and Letter Was Received":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Document And Letter Was Received And Under Review":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Filed Under Known Employer Pilot":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Fingerprint Fee Was Received":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Name Was Updated":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Request Was Processed":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Request Was Rejected":{"l1":"Received","l2":"Received","l3":"Received","l4":"Processing"},
    "Fee Refund Was Mailed":{"l1":"Refounded","l2":"Received","l3":"Received","l4":"Processing"},
    "Fee Will Be Refunded":{"l1":"Refounded","l2":"Received","l3":"Received","l4":"Processing"},
    "Premium Processing Fee Will Be Refunded":{"l1":"Refounded","l2":"Received","l3":"Received","l4":"Processing"},
    "Case Was Reopened":{"l1":"Reopened","l2":"Received","l3":"Received","l4":"Processing"},
    "Case Was Reopened For Reconsideration":{"l1":"Reopened","l2":"Received","l3":"Received","l4":"Processing"},
    "Response To USCIS' Notice of Intent to Revoke":{"l1":"ResponseReceived","l2":"Received","l3":"Received","l4":"Processing"},
    "Special Immigrant Juvenile Deferred Action Not Granted":{"l1":"ActionNotGranted","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Certified Approval Of My Case Was Reversed by The Appellate Authority":{"l1":"ApprovalReversed","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Certified Denial Of My Case Was Affirmed By Appellate Authority":{"l1":"DenialAffirmed","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Case Was Denied":{"l1":"Denied","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Case Was Denied And My Decision Notice Mailed":{"l1":"Denied","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Denial Was Upheld by Court":{"l1":"Denied","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Case Rejected Because I Sent An Incorrect Fee":{"l1":"Rejected","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Case Rejected Because The Version Of The Form I Sent Is No Longer Accepted":{"l1":"Rejected","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Case Rejected For Form Not Signed And Incorrect Form Version":{"l1":"Rejected","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Case Rejected For Incorrect Fee And Form Not Signed":{"l1":"Rejected","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Case Rejected For Incorrect Fee And Incorrect Form Version":{"l1":"Rejected","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Case Rejected For Incorrect Fee And Payment Not Signed":{"l1":"Rejected","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Case Rejected For Incorrect Fee, Payment Not Signed And Incorrect Form Version":{"l1":"Rejected","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Case Was Rejected Because I Did Not Sign My Form":{"l1":"Rejected","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Case Was Rejected Because It Was Improperly Filed":{"l1":"Rejected","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Case Was Rejected Because My Check Or Money Order Is Not Signed":{"l1":"Rejected","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "CNMI Semiannual Report Rejected":{"l1":"Rejected","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Form G-28 Was Rejected Because It Was Improperly Filed":{"l1":"Rejected","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Petition/Application Was Rejected For Insufficient Funds":{"l1":"Rejected","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Case Approval Was Revoked":{"l1":"Revoked","l2":"Rejected","l3":"Rejected","l4":"Final"},
    "Document Is Being Held For 180 Days":{"l1":"ReturnHold","l2":"ReturnHold","l3":"Other","l4":"Final"},
    "Document Was Returned As Undeliverable":{"l1":"ReturnHold","l2":"ReturnHold","l3":"Other","l4":"Final"},
    "Document Was Returned To USCIS":{"l1":"ReturnHold","l2":"ReturnHold","l3":"Other","l4":"Final"},
    "Document Was Returned To USCIS And Is Being Held":{"l1":"ReturnHold","l2":"ReturnHold","l3":"Other","l4":"Final"},
    "Response To USCIS' Request For Evidence Was Received":{"l1":"ResponseReceived","l2":"RFE_Received","l3":"RFE","l4":"Processing"},
    "Request for Additional Information Received":{"l1":"RFE_Received","l2":"RFE_Received","l3":"RFE","l4":"Processing"},
    "Request For Information Was Received And A Fax Reply Was Sent":{"l1":"RFE_Received","l2":"RFE_Received","l3":"RFE","l4":"Processing"},
    "Request for Additional Evidence Was Sent":{"l1":"RFE_Sent","l2":"RFE_Sent","l3":"RFE","l4":"Processing"},
    "Request for Initial and Additional Evidence Was Mailed":{"l1":"RFE_Sent","l2":"RFE_Sent","l3":"RFE","l4":"Processing"},
    "Request for Initial Evidence Was Sent":{"l1":"RFE_Sent","l2":"RFE_Sent","l3":"RFE","l4":"Processing"},
    "Special Immigrant Juvenile Deferred Action Terminated":{"l1":"ActionTernimated","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Card Destroyed":{"l1":"Destroyed","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Card Was Destroyed":{"l1":"Destroyed","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Document Destroyed":{"l1":"Destroyed","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Document Was Destroyed After USCIS Held It For 180 Days":{"l1":"Destroyed","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Document Was Destroyed And Letter Was Received":{"l1":"Destroyed","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Travel Document Was Destroyed":{"l1":"Destroyed","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Travel Document Was Destroyed After USCIS Held It For 180 Days":{"l1":"Destroyed","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Appeal Was Dismissed":{"l1":"Dismissed","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Student Employment Authorization Document Automatically Terminated":{"l1":"EAD_Terminated","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Case Is No Longer On Hold Because Of Pending Litigation":{"l1":"NotHold","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Termination Of Litigation Notice Was Mailed":{"l1":"NoticeSent","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Card Is Being Returned to USCIS by Post Office":{"l1":"ReturnedToUSCIS","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Card Was Returned To USCIS":{"l1":"ReturnedToUSCIS","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Notice Was Returned To USCIS Because The Post Office Could Not Deliver It":{"l1":"ReturnedToUSCIS","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Travel Document Was Returned to USCIS And Will Be Held For 180 Days":{"l1":"ReturnHold","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Case Was Automatically Revoked":{"l1":"Revoked","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Revocation Notice Was Sent":{"l1":"Revoked","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Appeal Was Terminated and A Notice Was Mailed To Me":{"l1":"Terminated","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Case Closed Benefit Received By Other Means":{"l1":"Terminated","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Petition Business Terminated/Over 180 Days/Not Automatically Revoked":{"l1":"Terminated","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Termination Notice Sent":{"l1":"Terminated","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Petition Withdrawn/Over 180 Days/Not Automatically Revoked":{"l1":"Withdrawn","l2":"Terminated","l3":"Rejected","l4":"Final"},
    "Case Transferred And New Office Has Jurisdiction":{"l1":"Transferred","l2":"Transferred","l3":"Transferred","l4":"Processing"},
    "Case Transferred To Another Office":{"l1":"Transferred","l2":"Transferred","l3":"Transferred","l4":"Processing"},
    "Case Was Relocated From Administrative Appeals Office To USCIS Originating Office":{"l1":"Transferred","l2":"Transferred","l3":"Transferred","l4":"Processing"},
    "Case Was Sent To The Administrative Appeals Office for Review":{"l1":"Transferred","l2":"Transferred","l3":"Transferred","l4":"Processing"},
    "Case Was Sent To The Department of State":{"l1":"Transferred","l2":"Transferred","l3":"Transferred","l4":"Processing"},
    "Case Was Sent To The Executive Office of Immigration Review":{"l1":"Transferred","l2":"Transferred","l3":"Transferred","l4":"Processing"},
    "Case Was Transferred And A New Office Has Jurisdiction":{"l1":"Transferred","l2":"Transferred","l3":"Transferred","l4":"Processing"},
    "Case Was Transferred To An Asylum Office":{"l1":"Transferred","l2":"Transferred","l3":"Transferred","l4":"Processing"},
    "Case Was Transferred To International Office/Consulate":{"l1":"Transferred","l2":"Transferred","l3":"Transferred","l4":"Processing"},
    "Department of State Sent Case to USCIS For Review":{"l1":"Transferred","l2":"Transferred","l3":"Transferred","l4":"Processing"},
    "Withdrawal Acknowledgement Notice Was Sent":{"l1":"WithdrawalAcknowledged","l2":"WithdrawalAcknowledged","l3":"Other","l4":"Other"},
    "Withdrawal Of My Appeal Was Acknowledged":{"l1":"WithdrawalAcknowledged","l2":"WithdrawalAcknowledged","l3":"Other","l4":"Other"}
}
